services:
  db:
    image: postgres:17
    container_name: workly_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workly_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  arch:
    image: postgres:17
    container_name: arch_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: arch_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_arch:/var/lib/postgresql/data


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: workly_backend
    restart: always
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      DB_URL: postgresql+asyncpg://postgres:postgres@db:5432/workly_db
    command: >
      sh -c "python certs.py &&
            alembic upgrade head &&
            uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/app
volumes:
  postgres_data:
  postgres_data_arch:
